function make_extended_figures()
%MAKE_EXTENDED_FIGURES
% Generate the mechanism-control and graded-landscape manuscript figures.
%
% Outputs:
%   Fig_3   A-B baseline trajectories from the quality-dynamics analysis; C-D mechanism-control quality
%   Fig_4   graded task structure: quality + common-scale component accuracy
%   Fig_S2  mechanism-control effects relative to matched baseline
%   Fig_S3  functional vs structural lineage depth across graded task structure
%
% Fig_1, Fig_2, and Fig_S1 are generated by make_baseline_figures.
%
% Expected result files:
%   results/mechanism_controls/quality_dynamics_results.mat
%   results/mechanism_controls/mechanism_controls_results.mat
%   results/graded_task_landscapes/graded_task_landscapes_results.mat

clc;
rootDir   = repository_root();
resultDir = fullfile(rootDir,'results');
figureDir = fullfile(rootDir,'figures');
outDir    = fullfile(figureDir,'manuscript');
if ~exist(outDir,'dir'), mkdir(outDir); end

dynamicsFile = fullfile(resultDir, 'mechanism_controls', ...
    'quality_dynamics_results.mat');
mechanismFile = fullfile(resultDir, 'mechanism_controls', ...
    'mechanism_controls_results.mat');
landscapeFile = fullfile(resultDir, 'graded_task_landscapes', ...
    'graded_task_landscapes_results.mat');

mustExist(dynamicsFile);
mustExist(mechanismFile);
mustExist(landscapeFile);

Ddyn = load(dynamicsFile);
Dctrl = load(mechanismFile);
Dland = load(landscapeFile);
STYLE = publicationStyle();

plotFigure3(Ddyn,Dctrl,outDir,STYLE);
plotFigureS2MechanismDelta(Dctrl,outDir,STYLE);
plotFigure4(Dland,outDir,STYLE);
plotFigureS3Lineage(Dland,outDir,STYLE);

fprintf('\nExtended manuscript figures written to:\n%s\n',outDir);
fprintf('Generated: Fig_3, Fig_4, Fig_S2, Fig_S3 (.png, .pdf, .fig)\n');
end

function mustExist(f)
if ~exist(f,'file')
    error('Required result file not found:\n%s',f);
end
end

% =========================================================================
% FIGURE 3
% A-B baseline trajectories from the quality-dynamics analysis
% C-D mechanism-control final quality
% =========================================================================
function plotFigure3(Ddyn,Dctrl,outDir,STYLE)

cfgDyn = Ddyn.cfg;
cfgCtrl = Dctrl.cfg;
meanQualityTrajectory = Ddyn.meanQualityTrajectory;
socialCtrl = Dctrl.social;
controlNames = Dctrl.controlNames;

[~,imCtrl] = min(abs(cfgCtrl.muGrid-cfgCtrl.representativeMu));
[~,ipCtrl] = min(abs(cfgCtrl.phiGrid-cfgCtrl.representativePhi));

taskLabels = {'Smooth','Opaque','Strict sequence'};
controlLabels = {'Baseline','Random demonstrator','Random copy error','Greedy acceptance'};

fig = figure('Color','w','Position',[60 60 750 600], ...
    'Renderer','painters','InvertHardcopy','off');

left1 = 0.090; left2 = 0.555;
panelW = 0.355; panelH = 0.345;
topY = 0.575; bottomY = 0.110;

% A-B: baseline trajectories from the matched quality-dynamics run.
for it = 1:numel(cfgDyn.tauLevels)
    x0 = ternary(it==1,left1,left2);
    ax = axes('Parent',fig,'Position',[x0 topY panelW panelH]);
    hold(ax,'on');
    colors = ax.ColorOrder;
    h = gobjects(1,numel(cfgDyn.taskTypes));
    for ik = 1:numel(cfgDyn.taskTypes)
        X = squeeze(meanQualityTrajectory(:,:,it,ik));
        m = mean(X,2,'omitnan');
        se = std(X,0,2,'omitnan')./sqrt(sum(~isnan(X),2));
        lo = m-1.96*se; hi = m+1.96*se;
        c = colors(mod(ik-1,size(colors,1))+1,:);
        fill(ax,[(1:cfgDyn.nGenerations) fliplr(1:cfgDyn.nGenerations)], ...
            [lo' fliplr(hi')],c,'FaceAlpha',0.15,'EdgeColor','none', ...
            'HandleVisibility','off');
        h(ik)=plot(ax,1:cfgDyn.nGenerations,m,'LineWidth',STYLE.LineWidth,'Color',c);
    end
    xlabel(ax,'Generation'); ylabel(ax,'Mean quality');
    xlim(ax,[1 cfgDyn.nGenerations]); ylim(ax,[0 1]);
    title(ax,sprintf('Baseline, \\tau = %.2f',cfgDyn.tauLevels(it)), ...
        'Interpreter','tex','FontWeight','normal');
    applyPublicationStyle(ax,STYLE); axis(ax,'square');
    addPanelLabel(ax,char('A'+it-1),STYLE);
    lgd=legend(ax,h,taskLabels,'Box','off','Interpreter','none');
    set(lgd,'FontName',STYLE.FontName,'FontSize',STYLE.LegendFontSize, ...
        'Units','normalized','Position',[x0+0.235 0.75 0.145 0.090]);
end

% C-D: final mean quality under mechanism controls.
for it = 1:numel(cfgCtrl.tauLevels)
    x0 = ternary(it==1,left1,left2);
    ax = axes('Parent',fig,'Position',[x0 bottomY panelW panelH]);
    hold(ax,'on');
    hh = gobjects(1,numel(controlNames));
    for ic = 1:numel(controlNames)
        m = nan(1,numel(cfgCtrl.taskTypes)); e = m;
        for ik = 1:numel(cfgCtrl.taskTypes)
            x = squeeze(socialCtrl.finalMean(:,imCtrl,ipCtrl,it,ik,ic));
            [m(ik),e(ik)] = meanAndCIHalfWidth(x);
        end
        hh(ic)=errorbar(ax,1:numel(cfgCtrl.taskTypes),m,e,'-o', ...
            'LineWidth',STYLE.LineWidth,'MarkerSize',STYLE.MarkerSize,'CapSize',0);
    end
    set(ax,'XTick',1:numel(taskLabels),'XTickLabel',taskLabels);
    xlim(ax,[0.75 numel(taskLabels)+0.25]); ylim(ax,[0 1]);
    ylabel(ax,'Final mean quality');
    title(ax,sprintf('Mechanism controls, \\tau = %.2f',cfgCtrl.tauLevels(it)), ...
        'Interpreter','tex','FontWeight','normal');
    applyPublicationStyle(ax,STYLE); axis(ax,'square');
    addPanelLabel(ax,char('C'+it-1),STYLE);
    if it==2
        lgd=legend(hh,controlLabels,'Orientation','horizontal','Box','off','Interpreter','none');
        set(lgd,'FontName',STYLE.FontName,'FontSize',STYLE.LegendFontSize, ...
            'Units','normalized','Position',[0.30 0.015 0.40 0.05]);
        lgd.ItemTokenSize=[24 8];
    end
end

exportFigure(fig,outDir,'Fig_3',STYLE); close(fig);
end

% =========================================================================
% FIGURE 4
% A-B task-specific final quality
% C-D mean component accuracy
% E-F best component accuracy
% all from the same graded-task run
% =========================================================================
function plotFigure4(D,outDir,STYLE)
cfg = D.cfg; social = D.social; levels = D.severityValues;
[~,im] = min(abs(cfg.muGrid-cfg.representativeMu));
[~,ip] = min(abs(cfg.phiGrid-cfg.representativePhi));

fig=figure('Color','w','Position',[60 40 500 850], ...
    'Renderer','painters','InvertHardcopy','off');
xPos=[0.095 0.555]; yPos=[0.685 0.395 0.105]; panelW=0.345; panelH=0.245;
letters={'A','B','C','D','E','F'}; c=0; shared=gobjects(1,numel(cfg.tauLevels));
metrics={'finalMean','finalMeanComponentAccuracy','finalMaxComponentAccuracy'};
ylabels={'Final mean quality','Mean component accuracy','Best component accuracy'};

for row=1:3
    for iff=1:2
        c=c+1;
        ax=axes('Parent',fig,'Position',[xPos(iff) yPos(row) panelW panelH]); hold(ax,'on');
        lev=levels{iff}; h=gobjects(1,numel(cfg.tauLevels));
        for it=1:numel(cfg.tauLevels)
            X=squeeze(social.(metrics{row})(:,im,ip,it,:,iff));
            m=mean(X,1,'omitnan');
            se=std(X,0,1,'omitnan')./sqrt(sum(~isnan(X),1));
            e=1.96*se;
            h(it)=errorbar(ax,lev,m,e,'-o','LineWidth',STYLE.LineWidth, ...
                'MarkerSize',STYLE.MarkerSize,'CapSize',0);
        end
        xlabel(ax,axisLabel(iff),'Interpreter','tex'); ylabel(ax,ylabels{row});
        xlim(ax,[min(lev) max(lev)]); ylim(ax,[0 1]);
        applyPublicationStyle(ax,STYLE); axis(ax,'square'); addPanelLabel(ax,letters{c},STYLE);
        if row==1 && iff==1, shared=h; end
    end
end
lgd=legend(shared,compose('\\tau = %.2f',cfg.tauLevels), ...
    'Orientation','horizontal','Box','off','Interpreter','tex');
set(lgd,'FontName',STYLE.FontName,'FontSize',STYLE.LegendFontSize, ...
    'Units','normalized','Position',[0.34 0.025 0.32 0.035]);
lgd.ItemTokenSize=[24 8];

exportFigure(fig,outDir,'Fig_4',STYLE); close(fig);
end

% =========================================================================
% SUPPLEMENTARY FIGURE S2
% Mechanism-control effects relative to matched baseline
% =========================================================================
function plotFigureS2MechanismDelta(D,outDir,STYLE)
cfg=D.cfg; social=D.social; controlNames=D.controlNames;
[~,im]=min(abs(cfg.muGrid-cfg.representativeMu));
[~,ip]=min(abs(cfg.phiGrid-cfg.representativePhi));
controlLabels={'Random demonstrator','Random copy error','Greedy acceptance'};
taskLabels={'Smooth','Opaque','Strict sequence'};
fig=figure('Color','w','Position',[60 60 750 380],'Renderer','painters','InvertHardcopy','off');
xPos=[0.090 0.555]; panelW=0.355; panelH=0.70; y0=0.165;
for it=1:numel(cfg.tauLevels)
    ax=axes('Parent',fig,'Position',[xPos(it) y0 panelW panelH]); hold(ax,'on');
    hh=gobjects(1,numel(controlNames)-1);
    for ic=2:numel(controlNames)
        m=nan(1,numel(cfg.taskTypes)); e=m;
        for ik=1:numel(cfg.taskTypes)
            x=squeeze(social.finalMean(:,im,ip,it,ik,ic));
            b=squeeze(social.finalMean(:,im,ip,it,ik,1));
            [m(ik),e(ik)]=meanAndCIHalfWidth(x-b);
        end
        hh(ic-1)=errorbar(ax,1:numel(cfg.taskTypes),m,e,'-o','LineWidth',STYLE.LineWidth,'MarkerSize',STYLE.MarkerSize,'CapSize',0);
    end
    plot(ax,[0.75 numel(taskLabels)+0.25],[0 0],'k--','LineWidth',STYLE.AxesLineWidth,'HandleVisibility','off');
    set(ax,'XTick',1:numel(taskLabels),'XTickLabel',taskLabels); xlim(ax,[0.75 numel(taskLabels)+0.25]);
    ylabel(ax,'Change in final mean quality'); title(ax,sprintf('\\tau = %.2f',cfg.tauLevels(it)),'Interpreter','tex','FontWeight','normal');
    applyPublicationStyle(ax,STYLE); axis(ax,'square'); addPanelLabel(ax,char('A'+it-1),STYLE);
    if it==2
        lgd=legend(hh,controlLabels,'Orientation','horizontal','Box','off','Interpreter','none');
        set(lgd,'FontName',STYLE.FontName,'FontSize',STYLE.LegendFontSize,'Units','normalized','Position',[0.30 0.02 0.40 0.05]);
        lgd.ItemTokenSize=[24 8];
    end
end
exportFigure(fig,outDir,'Fig_S2',STYLE); close(fig);
end

% =========================================================================
% SUPPLEMENTARY FIGURE S3
% A-B functional ancestry; C-D structural ancestry
% =========================================================================
function plotFigureS3Lineage(D,outDir,STYLE)
cfg=D.cfg; social=D.social; levels=D.severityValues;
[~,im]=min(abs(cfg.muGrid-cfg.representativeMu));
[~,ip]=min(abs(cfg.phiGrid-cfg.representativePhi));

fig=figure('Color','w','Position',[60 60 750 650], ...
    'Renderer','painters','InvertHardcopy','off');
xPos=[0.090 0.555]; yPos=[0.565 0.110]; panelW=0.355; panelH=0.330;
metrics={'bestFunctionalLineageDepth','bestStructuralLineageDepth'};
ylabels={'Functional lineage depth, D_q','Structural lineage depth, D_m'};
letters={'A','B','C','D'}; cc=0; shared=[];
for row=1:2
    for iff=1:2
        cc=cc+1;
        ax=axes('Parent',fig,'Position',[xPos(iff) yPos(row) panelW panelH]); hold(ax,'on');
        lev=levels{iff}; h=gobjects(1,numel(cfg.tauLevels));
        for it=1:numel(cfg.tauLevels)
            X=squeeze(social.(metrics{row})(:,im,ip,it,:,iff));
            m=mean(X,1,'omitnan');
            se=std(X,0,1,'omitnan')./sqrt(sum(~isnan(X),1));
            h(it)=errorbar(ax,lev,m,1.96*se,'-o','LineWidth',STYLE.LineWidth, ...
                'MarkerSize',STYLE.MarkerSize,'CapSize',0);
        end
        xlabel(ax,axisLabel(iff),'Interpreter','tex'); ylabel(ax,ylabels{row},'Interpreter','tex');
        xlim(ax,[min(lev) max(lev)]);
        applyPublicationStyle(ax,STYLE); axis(ax,'square'); addPanelLabel(ax,letters{cc},STYLE);
        if row==1 && iff==1, shared=h; end
    end
end
lgd=legend(shared,compose('\\tau = %.2f',cfg.tauLevels), ...
    'Orientation','horizontal','Box','off','Interpreter','tex');
set(lgd,'FontName',STYLE.FontName,'FontSize',STYLE.LegendFontSize, ...
    'Units','normalized','Position',[0.34 0.025 0.32 0.035]);
lgd.ItemTokenSize=[24 8];
exportFigure(fig,outDir,'Fig_S3',STYLE); close(fig);
end

function s=axisLabel(iff)
if iff==1
    s = 'Opacity weight, \lambda';
else
    s = 'Sequence-dependence weight, \omega';
end
end

function STYLE=publicationStyle()
STYLE.FontName='Times New Roman'; STYLE.TickFontSize=9; STYLE.LabelFontSize=10;
STYLE.LegendFontSize=9; STYLE.SuperTitleFontSize=11.5; STYLE.AxesLineWidth=0.5;
STYLE.LineWidth=1.0; STYLE.MarkerSize=3; STYLE.TickLength=[0.01 0.01]; STYLE.PNGResolution=600;
end

function applyPublicationStyle(ax,S)
set(ax,'FontName',S.FontName,'FontSize',S.TickFontSize,'LineWidth',S.AxesLineWidth, ...
    'TickDir','out','TickLength',S.TickLength,'Box','off','Layer','top', ...
    'XMinorTick','off','YMinorTick','off'); grid(ax,'off');
end

function addPanelLabel(ax,t,S)
text(ax,-0.18,1.10,t,'Units','normalized','FontName',S.FontName, ...
    'FontSize',S.SuperTitleFontSize,'FontWeight','bold', ...
    'HorizontalAlignment','left','VerticalAlignment','top','Interpreter','none');
end

function [m,e]=meanAndCIHalfWidth(x)
x=x(:); x=x(~isnan(x)); m=mean(x); e=1.96*std(x,0)/sqrt(numel(x));
end

function exportFigure(fig,outDir,stem,S)
savefig(fig,fullfile(outDir,[stem '.fig']));
try
    exportgraphics(fig,fullfile(outDir,[stem '.png']),'Resolution',S.PNGResolution,'BackgroundColor','white');
    exportgraphics(fig,fullfile(outDir,[stem '.pdf']),'ContentType','vector','BackgroundColor','white');
catch ME
    warning('exportgraphics failed (%s). Falling back to print().',ME.message);
    set(fig,'PaperPositionMode','auto');
    print(fig,fullfile(outDir,[stem '.png']),'-dpng',sprintf('-r%d',S.PNGResolution));
    try
        print(fig,fullfile(outDir,[stem '.pdf']),'-dpdf','-painters','-bestfit');
    catch
        print(fig,fullfile(outDir,[stem '.pdf']),'-dpdf','-painters');
    end
end
end

function out=ternary(cond,a,b)
if cond, out=a; else, out=b; end
end
