function rootDir = setup_project()
%SETUP_PROJECT Add repository MATLAB code to the path and create output folders.

rootDir = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(rootDir,'matlab')));

requiredDirs = { ...
    fullfile(rootDir,'data'), ...
    fullfile(rootDir,'results'), ...
    fullfile(rootDir,'results','baseline'), ...
    fullfile(rootDir,'results','mechanism_controls'), ...
    fullfile(rootDir,'results','discrimination_sensitivity'), ...
    fullfile(rootDir,'results','graded_task_landscapes'), ...
    fullfile(rootDir,'figures'), ...
    fullfile(rootDir,'figures','manuscript')};

for i = 1:numel(requiredDirs)
    if ~exist(requiredDirs{i},'dir')
        mkdir(requiredDirs{i});
    end
end

fprintf('Cumulative-cultural-dynamics repository configured:\n%s\n',rootDir);
end
