function validate_outputs()
%VALIDATE_OUTPUTS Check the manuscript result package and figures.

rootDir = setup_project();
resultDir = fullfile(rootDir,'results');
figureDir = fullfile(rootDir,'figures','manuscript');

expectedFiles = { ...
    fullfile(resultDir,'baseline','baseline_grid_results.mat'), ...
    fullfile(resultDir,'baseline','baseline_conditions.csv'), ...
    fullfile(resultDir,'baseline','baseline_key_metrics.csv'), ...
    fullfile(resultDir,'baseline','threshold_summary.csv'), ...
    fullfile(resultDir,'mechanism_controls','quality_dynamics_results.mat'), ...
    fullfile(resultDir,'mechanism_controls','mechanism_controls_results.mat'), ...
    fullfile(resultDir,'mechanism_controls','mechanism_controls_full_grid.csv'), ...
    fullfile(resultDir,'mechanism_controls','mechanism_controls_representative.csv'), ...
    fullfile(resultDir,'discrimination_sensitivity','discrimination_sensitivity_results.mat'), ...
    fullfile(resultDir,'discrimination_sensitivity','beta_sensitivity.csv'), ...
    fullfile(resultDir,'discrimination_sensitivity','gamma_sensitivity.csv'), ...
    fullfile(resultDir,'graded_task_landscapes','graded_task_landscapes_results.mat'), ...
    fullfile(resultDir,'graded_task_landscapes','opacity_results.csv'), ...
    fullfile(resultDir,'graded_task_landscapes','sequence_dependence_results.csv'), ...
    fullfile(resultDir,'graded_task_landscapes','common_scale_validation.csv'), ...
    fullfile(resultDir,'graded_task_landscapes','lineage_depth_results.csv')};

for i = 1:numel(expectedFiles)
    assert(exist(expectedFiles{i},'file') == 2,'Missing result/output file: %s',expectedFiles{i});
end

figureStems = {'Fig_1','Fig_2','Fig_3','Fig_4','Fig_S1','Fig_S2','Fig_S3'};
extensions = {'.png','.pdf','.fig'};
for i = 1:numel(figureStems)
    for j = 1:numel(extensions)
        f = fullfile(figureDir,[figureStems{i} extensions{j}]);
        assert(exist(f,'file') == 2,'Missing figure file: %s',f);
    end
end

% Core manuscript parameter checks.
B = load(fullfile(resultDir,'baseline','baseline_grid_results.mat'),'cfg');
assert(B.cfg.nAgents == 30);
assert(B.cfg.nGenerations == 80);
assert(B.cfg.nSeeds == 100);
assert(B.cfg.seqLength == 10);
assert(B.cfg.alphabetSize == 5);
assert(isequal(B.cfg.muGrid,[0 0.03 0.08 0.15]));
assert(isequal(B.cfg.phiGrid,[0.45 0.65 0.80 0.92 0.98]));
assert(isequal(B.cfg.tauLevels,[0 0.60]));

fprintf('Validated %d result/CSV files and %d manuscript figures.\n', ...
    numel(expectedFiles),numel(figureStems));
end
